package com.finance.core.domain;

public enum AuditActionType {
    PORTFOLIO_CREATED,
    PORTFOLIO_VISIBILITY_CHANGED,
    PORTFOLIO_DEPOSITED,
    PORTFOLIO_DELETED,
    TRADE_BUY_EXECUTED,
    TRADE_SELL_EXECUTED,
    USER_FOLLOWED,
    USER_UNFOLLOWED,
    ANALYSIS_POST_CREATED,
    ANALYSIS_POST_DELETED,
    INTERACTION_LIKED,
    INTERACTION_UNLIKED,
    INTERACTION_COMMENTED,
    STRATEGY_BOT_CREATED,
    STRATEGY_BOT_UPDATED,
    STRATEGY_BOT_DELETED,
    STRATEGY_BOT_RUN_REQUESTED,
    STRATEGY_BOT_RUN_STARTED,
    STRATEGY_BOT_RUN_EXECUTED,
    STRATEGY_BOT_RUN_RECONCILED
}
